### ISSUE TITLE
508 Compliance Errors - PWS Compliance

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#26]
- [x] Code Sniffer is giving the error for the Contact Information header in the footer, saying “The heading structure is not logically nested. This h3 element appears to be the primary document heading, so should be an h1 element.” Let’s discuss in our standup.
- [x] The other 508 errors seem to arise from the Twitter embed. Please swap out the Twitter iFrame with current User timeline as listed in the following docs:
  https://dev.twitter.com/web/embedded-timelines/user
  https://dev.twitter.com/web/embedded-timelines

**Comment by bmallred** [comment]
So in the [src/templates/fedramp.html](../blob/master/src/templates/fedramp.html#L73) we have the anchor tag with the values available at the links provided in the issue.

```
<twitter>
    <a class="twitter-timeline" href="https://twitter.com/FedRAMP" data-tweet-limit="1">Tweets by @FedRAMP</a>
</twitter>
```

For a complete reference to the code you can check it out at [Twitter](https://publish.twitter.com?url=https%3A%2F%2Ftwitter.com%2FFedRAMP#). There code snippet looks like the following:

```
<a class="twitter-timeline" href="https://twitter.com/FedRAMP">Tweets by FedRAMP</a>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

The JavaScript insertion we had to do something to get around because Angular is cautious about script elements in views. We did this by dynamically adding the element to the body in the [Twitter component](../blob/master/src/fedramp.components/twitter.component.js)

**Comment by bmallred** [comment]
We converted the `<h3>` elements in the footer to `<h1>` and then applied the same styling.

**Comment by lauraGgit** [comment]
Can confirm `h1` issue closed and other errors are generated by Twitter and therefore ok.
